### ISSUE TITLE
Convert PHP Code Migration

### ISSUE THREAD

**Issue by aregowe** [magento/code-migration#88]
Hi, I'm trying to run the final migration, the PHP code migration, and this is what I run into.

I ran:

`php bin/migrate.php convertPhpCode dst m1 m2`

And this is what shows in my command prompt:

```
C:\Users\Janderson\Documents\xampp\htdocs\code-migration>php bin/migrate.php convertPhpCode dst m1 m2
[2017-11-15 00:00:35][INFO]: Processing file dst/app/code/Amasty/Base/Block/Conflicts.php
[0;33m[2017-11-15 00:00:35][WARNING]: <?xml version="1.0"?> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">     <default>         <awall>             <feed>                 <url>ecommerce.aheadworks.com/blog/feed/?tag=feed&community=1</url>                 <use_https>0</use_https>                 <check_frequency>86400</check_frequency>                 <enabled>1</enabled>                 <interests>INFO,PROMO,UPDATE_RELEASE,NEW_RELEASE,INSTALLED_UPDATE</interests>             </feed>         </awall>     </default> </config>  is not a valid xml file or couldn't be loaded[0m
PHP Fatal error:  Uncaught Error: Call to a member function children() on null in C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Utility\M1\Config.php:128
Stack trace:
#0 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Mapping\Alias.php(162): Magento\Migration\Utility\M1\Config->getModuleName()
#1 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Mapping\Alias.php(103): Magento\Migration\Mapping\Alias->getAliasesFromFiles(Array)
#2 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Mapping\Alias.php(90): Magento\Migration\Mapping\Alias->processMappingFromM1PathConverted()
#3 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Code\Processor\ClassNameValidator.php(74): Magento\Migration\Mapping\Alias->getAllMapping()
#4 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Code\Processor\ClassNameValidator.php(52): Magento\Migration\Code\Processor\ClassNameVa in C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Utility\M1\Config.php on line 128

Fatal error: Uncaught Error: Call to a member function children() on null in C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Utility\M1\Config.php:128
Stack trace:
#0 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Mapping\Alias.php(162): Magento\Migration\Utility\M1\Config->getModuleName()
#1 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Mapping\Alias.php(103): Magento\Migration\Mapping\Alias->getAliasesFromFiles(Array)
#2 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Mapping\Alias.php(90): Magento\Migration\Mapping\Alias->processMappingFromM1PathConverted()
#3 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Code\Processor\ClassNameValidator.php(74): Magento\Migration\Mapping\Alias->getAllMapping()
#4 C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Code\Processor\ClassNameValidator.php(52): Magento\Migration\Code\Processor\ClassNameVa in C:\Users\Janderson\Documents\xampp\htdocs\code-migration\src\Magento\Migration\Utility\M1\Config.php on line 128

C:\Users\Janderson\Documents\xampp\htdocs\code-migration>
```

Any ideas?

Thank you.

**Comment by gordonknoppe** [comment]
Hi there, sorry about the non-answer but from the filename I can see that you're trying to convert a third-party extension (I see both Amasty and Aheadworks in that snippet).  You should only be running the converter on your own custom code and downloading the new, supported editions of those extensions from the vendor.
